version: '3'

services:
  # db:
  #   image: mysql:8.0
  #   restart: always
  #   ports:
  #     - "3306:3306"
  #   env_file:
  #     - .env
  #   environment:
  #     - MYSQL_ROOT_USER=${DB_USER}
  #     - MYSQL_ROOT_PASSWORD=${DB_PASSWD}
  #     - MYSQL_DATABASE=${DB_NAME}
  #   healthcheck:
  #     test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
  #     timeout: 20s
  #     retries: 10
  database:
    image: postgres:latest
    restart: always
    env_file:
      - .env
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWD}
      - POSTGRES_DB=${DB_NAME}
    ports:
      - '5432:5432'