name: Deploy master
on:
  push:
    branches:
    - main
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x]
    steps:
    - name: Checkout source code
      uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Make envfile
      uses: SpicyPizza/create-envfile@v1.3
      with:
        envkey_PORT: 3000
        envkey_HOST: 'http://localhost'
        envkey_APIROOT: '/api/v1'
        envkey_DB_USER: "root"
        envkey_DB_PASSWD: "abastosadmin"
        envkey_DB_NAME: "abastos"
        envkey_DB_PORT: "5432"  
        envkey_DB_TYPE: "postgres"
        envkey_TOKEN_SECRET: "AB@STOS_@PP"
        envkey_SALT_ROUNDS: 8
        envkey_EXPIRE_TOKEN: "8h"
        envkey_MAGIC_WORD: "Bearer"
        envkey_HEADER_JWT: "authorization"
        envkey_DB_HOST: "rds-abastos.chk9upbsd9cx.us-east-1.rds.amazonaws.com"
        directory: .
        file_name: .env
        fail_on_empty: false
    - name: npm install
      run: |
        npm ci
        npm install
    - name: generate dist
      run: npm run build --if-present
    - name: Generate deployment package
      run: zip -r deploy_package.zip . -x '*.git*' -x node_modules/\* -x src/\*
    - name: Deploy to EB
      uses: einaregilsson/beanstalk-deploy@v21
      with:
        aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        application_name: abastosappp
        environment_name: Abastosappp-env
        version_label: ver-${{ github.sha }}
        region: us-east-1
        deployment_package: deploy_package.zip
    - name: Deployed!
      run: echo App deployed to ELB